### PR TITLE
Clean up some stuff

### PR DESCRIPTION
**Pull request by jspawar**
Cleaning up some stuff, some of it is straightforward, some of it y'all might not be happy with thus the PR.

Please review the following summary (which is also the commit message of the first commit):

- Updated installation of `homebrew`
  - There's some new installation script that the old way told me to use
  via some deprecation message
- Remove unused brew installations
- Temporarily remove `gcloud` completion since it seems unused and we
don't actually install `gcloud` with the workspace
  - Will add `gcloud` installation in a later commit though
- Removed the following because nobody seems to use/many of us have
voiced frustration with:
  - Daily installation logic
  - Radar
  - jarg (for creating JSON objects)
  - uaac (there's supposed to be a go CLI too; should check it out)
  - CATs local setup thing? (seems like we always just defer to the
  pipeline)
  - The `httpie` plugin for the CF CLI
  - Whatever `hey` is
- Removed some potentially controversial things:
  - Running the mysql and postgres brew services
    - I think this should be an opt-in and not a constant default
    because it'll explode workstations and also force us to understand
    our tests better (e.g. that they're not really unit tests)
  - The `httpie` plugin for the CF CLI
    - CAPI team doesn't use it; however, VAT folks might?
  - The various better `grep` clones like `ag` because we install
  `ripgrep` which appears to have better support

ok thx

### CODE REVIEW

**Comment by cwlbraa** [comment]
> Daily installation logic

What is the frustration here? This works when capi-workspace is clean, and if we sucessfully pare down the repo that should be much easier for folks.

> CATs local setup thing? (seems like we always just defer to the
pipeline)

I never defer to the pipeline. I'm also not sure what you mean here -- are you just talking about deleting scripts? In the changed files you don't remove this.

**Comment by jspawar** [comment]
> What is the frustration here? This works when capi-workspace is clean, and if we sucessfully pare down the repo that should be much easier for folks.

I think a good majority of us have one-off changes to capi-workspace to fix a myriad of things as stop-gaps until we do that big refactor, problem there being the daily run sometimes clobbers that. It also doesn't seem very in-line with the notion of "minimal" or an unspoken desire of customizable/overrideable. 

> I never defer to the pipeline. I'm also not sure what you mean here -- are you just talking about deleting scripts? In the changed files you don't remove this.

Ya just removing scripts that nobody seems to use. I removed the call to run that thing in `install.sh` but you're right I did leave the file itself still there. 

> This is one of the things that breaks frequently for some folks? It seems a bit strange to have a workstation setup where a complete setup doesn't get us running unit tests.

I would really strongly prefer to make this an opt-in, this is not the only way to run the unit tests and I certainly think some folks would prefer something that is not the most heavy-handed way to run them (e.g. `docker run postgres`).

Also, again, I want to make this very clear to CAPI developers that we are using a real database with our "unit" tests so they understand various different potential failure modes of those tests (e.g. test pollution, random flakes, surfacing new potential failures)

**Comment by cwlbraa** [comment]
down to remove the autoinstall, at least for now... I think you're probably right that it causes more harm than good. It's too cute to actually be useful. It might be nice if you removed it in a commit separate to the big "remove everything" commit, just so future capi-ans might be able to benefit from its implementation. 

the cats thing you removed is unrelated to the thing I use. nice find, didn't even know it was there. 

> some folks would prefer something that is not the most heavy-handed way to run them (e.g. docker run postgres).

If you don't like the way we run these services now, you should 100% replace what we have with your preferred method. I don't think anyone is married to `brew services` or the shitwagon of accumulated scripts we've built around it. This comes across an argument to improve local database service management, not remove it. 

> I want to make this very clear to CAPI developers that we are using a real database

Is this really unclear to CAPI-ans? does this come from some other development background? I might be biased from being around capi-descendant teams for so long, but do folks really assume that our tests are using an in-memory database? 

CAPI tests use real DBs and transaction isolation. If new team members don't learn that almost immediately via pairing, I'm not sure all of us typing `docker run postgres` after every restart is going to teach them that.

**Comment by jspawar** [comment]
> If you don't like the way we run these services now, you should 100% replace what we have with your preferred method. I don't think anyone is married to brew services or the shitwagon of accumulated scripts we've built around it. This comes across an argument to improve local database service management, not remove it.

Yea, to that effect I can replace those with utilities which run Docker-based DBs which are more lightweight and more isolated.

> Is this really unclear to CAPI-ans? does this come from some other development background? I might be biased from being around capi-descendant teams for so long, but do folks really assume that our tests are using an in-memory database?

I think some newer members are often surprised by the fact that we have these "unit" tests without any hitch and then one day their brew service crashes or something similar and they are surprised to learn they were never real unit tests. 

> CAPI unit tests use real DBs and transaction isolation. If new team members don't learn that almost immediately via pairing, I'm not sure all of us typing docker run postgres after every restart is going to teach them that.

I think they're still valuable (integration tests > unit tests IMO) however I think it's still confusing how all of these interactions work in our testing context. Hell even I am still personally confused about how it works. From my understanding we open one big transaction for each test, but what about when we explicitly open transactions in our code?

**Comment by cwlbraa** [comment]
> what about when we explicitly open transactions in our code

Most ORMs handle this reusing open transactions if you try to to nest them. I think Sequel does as well. In theory it makes it so that you can't test transaction granularity in "unit" tests -- ie injecting failure on transaction commits won't do what you think it'll do because test transactions commit at the end of the test context and then roll back. 

My impression is that a lot of this stuff is just developers with backgrounds in different languages come with different expectations about tests. We should probably do a better job setting expectations around the Rails-ish stuff we do, but for me personally it's hard to know what's standard railsey stuff vs what's crazy VCAP nonsense.

**Comment by JenGoldstrich** [comment]
Hey @jspawar! @sweinstein22 and I just updated capi-workspace to default to the main branch, and are in the process of deleting the master branch, if you'd still like to submit this PR can you rebase it on main and re-submit?

Thanks!
Jenna and Sarah

**Pull request closed without merging**
